"""modif nom inventory

Revision ID: b3b232423e94
Revises: fadaf30ac2f4
Create Date: 2023-09-04 08:08:14.701796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b232423e94'
down_revision = 'fadaf30ac2f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('inventory', sa.Integer(), nullable=True))
    op.drop_column('ingredient', 'innventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('innventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ingredient', 'inventory')
    # ### end Alembic commands ###
