"""avec lien categories

Revision ID: fadaf30ac2f4
Revises: 7f86d7b07686
Create Date: 2023-09-03 19:09:55.478997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadaf30ac2f4'
down_revision = '7f86d7b07686'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('categorie_id', sa.Integer(), nullable=True))
    op.drop_index('ix_ingredient_categorie', table_name='ingredient')
    op.create_foreign_key(None, 'ingredient', 'categories', ['categorie_id'], ['id'])
    op.drop_column('ingredient', 'categorie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('categorie', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_index('ix_ingredient_categorie', 'ingredient', ['categorie'], unique=False)
    op.drop_column('ingredient', 'categorie_id')
    # ### end Alembic commands ###
